## ============================================================
## run_06_deploy.R — build the self-contained bundle for hosting
## ------------------------------------------------------------
## A host gets ONE directory. `app/app.R` cannot be that directory: it
## reaches two levels up through BBALL_HOME to source Phases 3-6 and to
## read the cached assets, and none of those paths exist on a server.
##
## So this stages a copy that stands alone. It is generated, never edited —
## edit `app/app.R` and `scripts/r/06_winprob_calc.R` and rerun this.
##
## Three things it exploits, all measured rather than assumed:
##
##  - **Only Phase 6 is needed at runtime.** The app calls
##    load_winprob_fit(), secs_left_from_clock() and win_probability(),
##    all defined in 06. Phases 3-5 are sourced by app/app.R only because
##    WINPROB_ROOT happens to be defined in 03. Defining it here instead
##    drops three files.
##  - **Dropping 04 drops `arrow`.** rsconnect's dependency scan is
##    static, so a bundled 04_training_set.R would put arrow in the
##    manifest and into every deploy, for a function the app never calls.
##  - **The 58MB ratings CSV is not runtime.** run_06_prep.R already
##    reduced it to the 663-row board. Only the board and the fit ship.
##
## Leaves the data under `data/tidy/wbb/` so the copied 06 works BYTE FOR
## BYTE — load_winprob_fit() defaults to that subpath under WINPROB_ROOT.
## Rewriting paths in the copy would be the drift this is designed to avoid.
##
##   Rscript scripts/r/run_06_deploy.R
## ============================================================

R_HOME_DIR   <- Sys.getenv("BBALL_HOME", unset = "~/Desktop/Basketball Analytics")
WINPROB_ROOT <- file.path(R_HOME_DIR, "12_wbb_winprob_calc")

SRC_APP  <- file.path(WINPROB_ROOT, "app/app.R")
SRC_CALC <- file.path(WINPROB_ROOT, "scripts/r/06_winprob_calc.R")
DEPLOY   <- file.path(WINPROB_ROOT, "deploy")

## The bootstrap block in app/app.R, verbatim. Matching the exact text (not
## a regex over it) is the point: if app.R's header is ever reworked this
## fails loudly on the next deploy build instead of silently shipping an
## app that still tries to source four files from a Desktop path.
OLD_BOOTSTRAP <- paste(
  'R_HOME_DIR <- Sys.getenv("BBALL_HOME", unset = "~/Desktop/Basketball Analytics")',
  'for (f in c("03_team_ratings", "04_training_set", "05_winprob_model", "06_winprob_calc"))',
  '  source(file.path(R_HOME_DIR, "12_wbb_winprob_calc/scripts/r", paste0(f, ".R")))',
  sep = "\n")

## Shiny sets the working directory to the app directory before sourcing,
## on every host and on runApp() locally, so "." is the bundle root.
## `local = TRUE` is load-bearing. Shiny sources app.R into its own
## environment, but source() defaults to the GLOBAL one — so the functions
## from 06 would close over globalenv while WINPROB_ROOT sat in the app
## env, and load_winprob_fit()'s default argument would not find it. The
## original app/app.R got away without this only because WINPROB_ROOT was
## itself defined inside a sourced file, landing in the same global env.
NEW_BOOTSTRAP <- paste(
  '## --- generated by scripts/r/run_06_deploy.R — do not edit this copy ---',
  '## Self-contained: everything the app reads lives under the bundle root.',
  'WINPROB_ROOT <- normalizePath(".")',
  'source("R/06_winprob_calc.R", local = TRUE)',
  sep = "\n")

stopifnot(file.exists(SRC_APP), file.exists(SRC_CALC))

src <- readLines(SRC_APP, warn = FALSE)
txt <- paste(src, collapse = "\n")

if (!grepl(OLD_BOOTSTRAP, txt, fixed = TRUE))
  stop("app/app.R's bootstrap block has changed — update OLD_BOOTSTRAP in ",
       "run_06_deploy.R to match before deploying.", call. = FALSE)

out <- sub(OLD_BOOTSTRAP, NEW_BOOTSTRAP, txt, fixed = TRUE)

## ---- stage ----------------------------------------------------------

dir.create(file.path(DEPLOY, "R"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(DEPLOY, "data/tidy/wbb"), recursive = TRUE, showWarnings = FALSE)

writeLines(out, file.path(DEPLOY, "app.R"))

## team_names() is build-time only — run_06_prep.R uses it to write
## rating_board.csv, and the app then reads that CSV. But rsconnect's
## dependency scan is static, so its single `wehoop::` call puts wehoop and
## its whole tree (usethis, gert, rvest, data.table, ...) into the manifest:
## 84 packages instead of ~30, for a function no session ever calls. Stub it
## in the copy. Matched verbatim so a rewrite of the real one fails loudly
## here rather than silently restoring the dependency.
OLD_TEAM_NAMES <- paste(
  'team_names <- function(season = 2026) {',
  '  suppressWarnings(wehoop::load_wbb_team_box(seasons = season)) |>',
  '    transmute(team_id = as.character(team_id),',
  '              display = as.character(team_display_name),',
  '              short   = as.character(team_short_display_name)) |>',
  '    distinct(team_id, .keep_all = TRUE) |>',
  '    arrange(display)',
  '}',
  sep = "\n")

NEW_TEAM_NAMES <- paste(
  'team_names <- function(season = 2026) {',
  '  stop("team_names() is build-time only and is not shipped in the deployed ",',
  '       "bundle — the picker reads rating_board.csv.", call. = FALSE)',
  '}',
  sep = "\n")

calc <- paste(readLines(SRC_CALC, warn = FALSE), collapse = "\n")
if (!grepl(OLD_TEAM_NAMES, calc, fixed = TRUE))
  stop("team_names() in 06_winprob_calc.R has changed — update OLD_TEAM_NAMES ",
       "in run_06_deploy.R before deploying.", call. = FALSE)
calc <- sub(OLD_TEAM_NAMES, NEW_TEAM_NAMES, calc, fixed = TRUE)
writeLines(calc, file.path(DEPLOY, "R/06_winprob_calc.R"))

assets <- c("winprob_fit.rds", "rating_board.csv")
for (a in assets) {
  from <- file.path(WINPROB_ROOT, "data/tidy/wbb", a)
  if (!file.exists(from))
    stop("missing runtime asset: ", from, call. = FALSE)
  file.copy(from, file.path(DEPLOY, "data/tidy/wbb", a), overwrite = TRUE)
}

## ---- report ---------------------------------------------------------

files <- list.files(DEPLOY, recursive = TRUE, full.names = TRUE)
total <- sum(file.size(files))

message(sprintf("staged %s — %d files, %.1f MB", DEPLOY, length(files), total / 1e6))
for (f in sort(files))
  message(sprintf("  %-34s %7.1f KB",
                  sub(paste0(DEPLOY, "/"), "", f, fixed = TRUE), file.size(f) / 1e3))
message("\nruntime packages: shiny, dplyr, locfit, readr, tibble")
message("test it:  Rscript -e 'shiny::runApp(\"12_wbb_winprob_calc/deploy\")'")
