###############################################
# Title: Unrivaled Efficiency Landscape Plot
# Purpose: Visualizes 2025 Unrivaled Team Efficiency
# Data Source: CSV generated from unrivaled_efficiency.py (SportRadar API)
# Author: Alycia Webster
###############################################

###############################################
# 0. Load Required Packages
###############################################

library(dplyr)
library(ggplot2)
library(ggimage)
library(readr)
library(ggtext)

###############################################
# 0.1 Load Unrivaled Logo
###############################################

# Unrivaled official logo URL - update if needed
unrivaled_logo <- "https://www.unrivaled.basketball/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Funrivaled-logo.ece5e28c.png&w=256&q=75"

###############################################
# 1. Load Data from CSV
###############################################

# Where the input CSV is read from and where the PNG lands.
#   Default (nothing to set up): your Desktop -- the same place the Python
#   stat grabber wrote its CSV, so the two scripts line up with no setup.
#   Optional: set BBALL_HOME in ~/.Renviron to an analytics folder and these
#   route to <BBALL_HOME>/<league>/data|outputs/ instead.
league     <- "05_unrivaled"   # league folder this script belongs to
bball_home <- Sys.getenv("BBALL_HOME", unset = "")
data_dir   <- if (nzchar(bball_home)) file.path(bball_home, league, "data")    else "~/Desktop"
output_dir <- if (nzchar(bball_home)) file.path(bball_home, league, "outputs") else "~/Desktop"
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

# Read the CSV generated by the Python script
team_efficiency <- read_csv(file.path(data_dir, "Unrivaled_Efficiency_Mar3_2026_playoff_teams.csv"))

# Display the data
print("Loaded Unrivaled efficiency data:")
print(team_efficiency)

###############################################
# 2. Calculate League Averages for Crosshairs
###############################################

avg_ortg <- mean(team_efficiency$ortg, na.rm = TRUE)
avg_drtg <- mean(team_efficiency$drtg, na.rm = TRUE)

cat("\nLeague Averages:\n")
cat(sprintf("  Offensive Rating: %.2f\n", avg_ortg))
cat(sprintf("  Defensive Rating: %.2f\n", avg_drtg))

###############################################
# 3. Set Zoom Distance
###############################################

# Adjust this value to zoom in/out on the plot
# Smaller = more zoomed in, larger = more zoomed out
zoom_dist <- 12.5

# Calculate plot limits centered on averages
x_lims <- c(avg_ortg - zoom_dist, avg_ortg + zoom_dist)
y_lims <- c(avg_drtg + zoom_dist, avg_drtg - zoom_dist)

###############################################
# 4. Create the Plot
###############################################

# Define the logo HTML for the title
logo_html <- paste0("<img src='", unrivaled_logo, "' height='40' style='margin-bottom: -10px;' />&nbsp;")

# Create the efficiency landscape plot
ggplot(team_efficiency, aes(x = ortg, y = drtg)) +
  
  # Crosshairs at league average
  geom_vline(xintercept = avg_ortg, linetype = "dashed", color = "grey70") +
  geom_hline(yintercept = avg_drtg, linetype = "dashed", color = "grey70") +
  
  # Net Rating diagonal line
  geom_segment(
    aes(x = avg_ortg - zoom_dist, y = avg_drtg - zoom_dist, 
        xend = avg_ortg + zoom_dist, yend = avg_drtg + zoom_dist), 
    linetype = "dotted", color = "grey50"
  ) +
  
  # Team logos
  geom_image(aes(image = logo), size = 0.08, asp = 1.6) +
  
  # Set limits
  scale_x_continuous(limits = x_lims) +
  scale_y_reverse(limits = y_lims) +
  
  # Force square quadrants
  coord_fixed(ratio = 1) +
  
  # Net Rating annotations
  annotate(
    "text", 
    x = avg_ortg - (zoom_dist * 0.9), 
    y = avg_drtg - (zoom_dist * 0.9),
    label = "(+) Net Rating", 
    angle = -45, vjust = -0.5, color = "grey50", size = 2.5, fontface = "italic"
  ) +
  annotate(
    "text", 
    x = avg_ortg + (zoom_dist * 0.9), 
    y = avg_drtg + (zoom_dist * 0.9), 
    label = "(-) Net Rating", 
    angle = -45, vjust = 2, color = "grey50", size = 2.5, fontface = "italic"
  ) +
  
  # Labels and theme
  labs(
    title = "Unrivaled Efficiency Landscape",
    subtitle = "2026 Season | <span style='color:#5d5eaa; '>Standings Before Finals</span> | @webster_like_the_dictionary", 
    x = "Offensive Efficiency (Points Scored per 100 Possessions)", 
    y = "Defensive Efficiency (Points Allowed per 100 Possessions)", 
    # caption = "Data via SportRadar Unrivaled API | Inspired by Kirk Goldsberry" 
  ) +
  theme_classic() +
  theme(
    plot.margin = margin(t = 15, r = 20, b = 10, l = 20, unit = "pt"),  # Reduce side margins
    plot.title = element_text(face = "bold", size = 20, hjust = 0.5),
    # plot.subtitle = element_text(hjust = 0.5, size = 9, color = "grey40"),
    plot.subtitle = element_markdown(hjust = 0.5, size = 9),
    axis.title.x = element_text(margin = margin(t = 10, b = 15)),  # Add space above and below x-axis title
    axis.title.y = element_text(margin = margin(r = 10))  # Space to the right of y-axis title (pushes it away from plot)
    # plot.caption = element_text(color = "grey40")
  )

###############################################
# 5. Save the Plot
###############################################

out_png <- file.path(output_dir, "Unrivaled_Efficiency_Mar3_2026_playoff_teams.png")

ggsave(
  filename = out_png,
  plot = last_plot(),
  width = 10,       
  height = 7,       
  dpi = 300,        
  bg = NA    
)

cat("\n✅ Plot saved to ", out_png, "\n", sep = "")